import { z } from "zod";

export const ANVISA_LIMITS: Record<string, {
  auth: boolean;
  min: number;
  max: number | null;
  unit: string;
  norm: string;
}> = {
  vitamina_d3:        { auth: true,  min: 0, max: 50,    unit: 'mcg', norm: 'IN 28 Anexo IV — 50 mcg = 2.000 UI' },
  vitamina_a:         { auth: true,  min: 0, max: 3000,  unit: 'mcg', norm: 'IN 28 Anexo IV' },
  vitamina_c:         { auth: true,  min: 0, max: 1000,  unit: 'mg',  norm: 'IN 28 Anexo IV' },
  vitamina_e:         { auth: true,  min: 0, max: 1000,  unit: 'mg',  norm: 'IN 28 Anexo IV' },
  vitamina_b1:        { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 — NE' },
  vitamina_b2:        { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 — NE' },
  vitamina_b3:        { auth: true,  min: 0, max: 35,    unit: 'mg',  norm: 'IN 28 Anexo IV (NE)' },
  vitamina_b5:        { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 — NE' },
  vitamina_b6:        { auth: true,  min: 0, max: 100,   unit: 'mg',  norm: 'IN 28 Anexo IV' },
  vitamina_b7:        { auth: true,  min: 0, max: null,  unit: 'mcg', norm: 'IN 28 — NE' },
  vitamina_b9:        { auth: true,  min: 0, max: 400,   unit: 'mcg', norm: 'IN 28 Anexo IV (DFE)' },
  vitamina_b12:       { auth: true,  min: 0, max: null,  unit: 'mcg', norm: 'IN 28 — NE' },
  vitamina_k2:        { auth: true,  min: 0, max: null,  unit: 'mcg', norm: 'IN 28 — NE' },
  zinco:              { auth: true,  min: 0, max: 25,    unit: 'mg',  norm: 'IN 28 Anexo IV' },
  ferro:              { auth: true,  min: 0, max: 45,    unit: 'mg',  norm: 'IN 28 Anexo IV' },
  magnesio:           { auth: true,  min: 0, max: 750,   unit: 'mg',  norm: 'IN 28 Anexo IV (elementar)' },
  calcio:             { auth: true,  min: 0, max: 2500,  unit: 'mg',  norm: 'IN 28 Anexo IV' },
  selenio:            { auth: true,  min: 0, max: 200,   unit: 'mcg', norm: 'IN 28 Anexo IV' },
  iodo:               { auth: true,  min: 0, max: 600,   unit: 'mcg', norm: 'IN 28 Anexo IV' },
  manganes:           { auth: true,  min: 0, max: 2,     unit: 'mg',  norm: 'IN 28 Anexo IV' },
  cobre:              { auth: true,  min: 0, max: 0.9,   unit: 'mg',  norm: 'IN 28 Anexo IV' },
  cromo:              { auth: true,  min: 0, max: 200,   unit: 'mcg', norm: 'IN 28 Anexo IV' },
  boro:               { auth: true,  min: 0, max: 6,     unit: 'mg',  norm: 'IN 28 Anexo IV' },
  fosforo:            { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 — NE' },
  coenzima_q10:       { auth: true,  min: 0, max: 300,   unit: 'mg',  norm: 'IN 28 Anexo IV' },
  cafeina:            { auth: true,  min: 0, max: 210,   unit: 'mg',  norm: 'IN 28 Anexo IV (por dose)' },
  melatonina:         { auth: true,  min: 0, max: 0.21,  unit: 'mg',  norm: 'IN 102/2021 — exclusivo ≥19 anos' },
  luteina:            { auth: true,  min: 0, max: 30,    unit: 'mg',  norm: 'IN 28 Anexo IV' },
  zeaxantina:         { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 — NE' },
  astaxantina:        { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 — NE' },
  l_arginina:         { auth: true,  min: 0, max: 3000,  unit: 'mg',  norm: 'IN 28 Anexo IV' },
  taurina:            { auth: true,  min: 0, max: 3000,  unit: 'mg',  norm: 'IN 28 Anexo IV' },
  creatina:           { auth: true,  min: 0, max: 3000,  unit: 'mg',  norm: 'IN 28 Anexo IV' },
  l_triptofano:       { auth: true,  min: 0, max: 1000,  unit: 'mg',  norm: 'IN 28 Anexo IV' },
  l_tirosina:         { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 Anexo I (CAS 60-18-4)' },
  beta_alanina:       { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 102/2021' },
  leucina:            { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 Anexo I' },
  isoleucina:         { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 Anexo I' },
  valina:             { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 Anexo I' },
  l_cistina:          { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 Anexo I' },
  msm:                { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 Anexo I — NE' },
  acido_hialuronico:  { auth: true,  min: 50, max: null, unit: 'mg',  norm: 'IN 102/2021 — mín. 50 mg' },
  colageno_tipo2:     { auth: true,  min: 40, max: null, unit: 'mg',  norm: 'IN 28 — mín. 40 mg UC-II' },
  colageno_hidrolisado:{ auth: true, min: 0, max: null,  unit: 'mg',  norm: 'IN 28 Anexo I' },
  omega3_epa_dha:     { auth: true,  min: 0, max: 3000,  unit: 'mg',  norm: 'IN 28 Anexo IV (total)' },
  espirulina:         { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 Anexo I' },
  psyllium:           { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 Anexo I' },
  curcuma:            { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 102/2021' },
  ext_laranja_moro:   { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 336/2024' },
  cha_verde:          { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 Anexo I' },
  gengibre:           { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 Anexo I' },
  feno_grego:         { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'Parecer GEARE/GGALI 7/2022' },
  propolis:           { auth: true,  min: 0, max: null,  unit: 'mg',  norm: 'IN 28 Anexo I' },
  berberina:          { auth: false, min: 0, max: 0,     unit: 'mg',  norm: 'NÃO consta Anexo I IN 28' },
  queratina:          { auth: false, min: 0, max: 0,     unit: 'mg',  norm: 'NÃO consta Anexo I IN 28' },
  silicio_organico:   { auth: false, min: 0, max: 0,     unit: 'mg',  norm: 'NÃO consta Anexo I IN 28' },
  l_citrulina:        { auth: false, min: 0, max: 0,     unit: 'mg',  norm: 'Verificar Power BI ANVISA' },
};

export const VD_REFERENCE: Record<string, number> = {
  vitamina_a: 800,
  vitamina_c: 75,
  vitamina_d3: 5,
  vitamina_e: 10,
  vitamina_b1: 1.1,
  vitamina_b2: 1.3,
  vitamina_b3: 14,
  vitamina_b5: 5,
  vitamina_b6: 1.3,
  vitamina_b7: 30,
  vitamina_b9: 400,
  vitamina_b12: 2.4,
  calcio: 1000,
  ferro: 14,
  zinco: 8,
  magnesio: 320,
  selenio: 55,
  iodo: 150,
  manganes: 2.3,
  cobre: 0.9,
  cromo: 30,
};
