project_id = "lvptvswvqjhvobdvgfws"

[functions.validate-certificate]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.anvisa-sync]
verify_jwt = false

[functions.anvisa-powerbi-sync]
verify_jwt = false

[functions.anvisa-resolve-name]
verify_jwt = false

[functions.send-contract-email]
verify_jwt = false